language: node_js
node_js:
  - "9"
cache: #savea node modules så man slipper installera varje gång
  directories:
  - "node_modules"
before_deploy:
  -npm run prod
deploy:
  provider: heroku
  api_key: 
