language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
before_deploy:
- npm run prod
deploy:
  provider: heroku
  api_key:
    secure: 0glNlN7c/begfJMzGs5bdqMjC2jpx0jiK8cV5WUJMf/DJb9dw+o4SMB7wemwZGUgo1oqkYH+eTnHKYqx1F1V9/yOkXDaaiNCxl8dz+vE40AoOWgYmnjJoL1MMBB/1pOhuBD4T4tHF0cuXXVNenm/JHJyaRkoXHMbH5lzj+N/EPUDkGPm7b+try7FlYi6jMVk65B9DMQolNQQE2bp+tu8lxl5dOswAQ1kfyjxuxchV+3eJOknjpOxmklqmGchYTdE38mqP7/trCznb4QDhfxAsAC4hy0GuZCwLGdb/+nNR9oe4uXPVhRQdAzqD66mS+fhLDuZ6J8X8X9Tf0Y4sln2tHzconTSi5X1tfBNY5awfrnUJ2409Fen37adgjLiD4IuMHJLDDA6aJYnTR00jRMtmJxnr3S9eF2yIqG3lHnh4iuDL44+izQPxD2TUNJpx/t2jSIB6cJBWYbiPtsyr8+Py2gK4yWKfyjG7x3A9O04kOIzZUggO4oOxHnXWTpR2kIxqgxjzFqsKPa7vuLc0pK4nTrU77kHIEjk7pav95x4iqWlisYkx4LgsX31lPbJg8LNKUmCdLPO1hGFp4LWDloYSZacEL1AE1GwlrBc2TRZ0Q18+C1gS0f2KwFjR6ks7GZnTmiX6QDZcaCl85u8fK6qU2U2QwUQ7B6p7OoX7GM3FDA=
