language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
before_deploy:
- npm run prod
deploy:
  provider: heroku
  api_key:
    secure: KkRTttXTb/1Jo0NoCTA0+8HJ1HCJn2I8DcKgM0JiDYoz1d5izWpp83b2/8cQs4ePIpJ9gYuNrfBAtFP/YHF9LVB18OVJcaD3Yi736SXdYwEB/OVUPrud8sKc2rO8BFkVVKNlD7TAuYr5e5p6zeZJDdph+G1B53XdSqbzDvzqzZ5gdNApTeSXzxRQ9l2+e7FqvJoEFY48ZVWFiBmw3yYcSWh3Z2A6Mk7Clbo8O5G0Cf7g17XZLyhCdFcxIJ5x+8wm+i49Nnia8VtR0Yl2q9oMcBL93huCGtNp7nI5xVbr9Rqh3zVijTaH72HM9J1H+7KlQbmEjTsZYHESCANE+FPxmnxpasce9DYE7QUpBlswNFRawL5TYyAunZfh4JZbJ0f3ialcxk3l6lvgnIqnnta9mhnFcS3oQO5fCkm6SRE07LvHbnpSf3Yj4pC/krq1cE23PsYidLUJRSqtNu6qzhG2xrX3n6Bx8PhKDi43zgQNg3HWOd9BQICDHIesn44CNiGmt1XalK2wreoyGptayi7IR05mq7BTBu+BQ3OTK6htMSXtCpD7QB8jZqm15c36OCk7GzWPsvrZ2M3e6P740/hZaj/HdUbCOUeAmDn3+h2xQOFsvcx668CLCewI7qWHOjrlFz7htxwldDb96+4SW5eFwX659w8MHI8id2SzIZ3ACjk=
