language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
before_deploy:
- npm run prod
deploy:
  provider: heroku
  api_key:
    secure: o/rDo0P9/bEdPnEDKKuK+cBwo1liRFwCAFm4HxEx+G1dpOWXZ/lAeeSHnX8qWzT9Roxi7mo6HLznOwnSbhRp6FRRYBR5ARa4KdpwtH6PrBIc6WqcqU7KWaZuOuBtlCJ7FaFYEUjKBv+dNX/J1XHDp7qCxfymSwjw7BAIjW1bIbY18YesPhIA9vZ/nhbrjh2XTAhLKiggm/WASikXvZrNzjg8xjkmc/arWfg48WMIY3+gFUiVa3LsZmAxaABc+LYLNOORZEAB90FIK650HUQVpHLRY9a5xyUbY9DKynNXlLQM2Mr2FQZkc2o64fPdQH2tepWplGuiRLG5WCgN5DUyhGzoG/F+OFlXYAAn7fq095Tpm9ry5BmjFxOKQwDOmNx9Pc4C7yDblcLltt8z4OOcxJG8DKMmuroU9PwilkHmLtxVUkCedAtMyC+y9boM7Jigp90J9xMpFdN33qDwgyiuVxCZgd1DS9B8xP5b+vNuJZNpWcT+CNzkK+FvgjyG9g/PUaGLFsNk4QthdNBX0geyhilF4baueSeXlD6FGCKEzebQkF+fVFvDdoxFYT6Wl2qskQuEU3HtKpCv6fZAUY6VHMDSdB7FdpWzM6rhBpA1Jemk/U4UaEQynIAtOIdjgKYkOP8rgN7VQb8bBIivTmspj8snjx9iC75jdRMaYpQuin4=
  app: pricehistoryapp
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
