language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
before_deploy:
- npm run prod
deploy:
  provider: heroku
  api_key:
    secure:  iubH9EShRouzsvYfVggZOquk+UIJFzsVVK9Oc5OoJU53fF7uTQSRcNo9/ZLUU2oemus0LuNx03kCHG/K/nEN0yfbW9yYAegZ4rCl/MlFi6Q5ekMCPpRy4SsP0Ms5YjAYRM/enxWWZQWROjDib/KF63n04r8Yp6YxyoFgIw2oKL52VPf/+UzjNpYFz8sL2wEdaEqSLitUJlRKHLxgmyWZ23tBZpN10n+ScGy0hLXuJ6TdZXMrzSPCfsJKMorWiRnjq4AftMnL7vME4EgcxW9q/93DZfSjqHaD96xZ5YQgjOQWUjf/wHgo0oOjGWOb+dP7p5C1o0FKuvrVSPFJs8EgX8hn+/Mef4WWkDP0cGbpdhxAR5W51VKKIJn0fcpRrXYKjqnqG8yJYI007iRFeaeq2pjuhKkxizrDXEpR/6j4yq1nywE5HgHXed243rBz5j8I+J0TOZeJXL/fVgEFjkEqStGrwwd+BpwbP1Ug/dZsttlROBKaDsiq/vCf7ASEdr9kPhlxA4IN6mc96NbW/SLEcrnvJozW80QQakIo5mBxGfO40Brq+2D/gQg3eQ/tuoMyKU7Yk6J259yo9zNe2J8gRfQxP/QFSe+/A79qLgMwICeOL9LoKTQ6ZpzFNFYt728JUtvJvdew++pDa2fW17GTyJXSE8VpVmrY8Moh4BuqJ3c=
    app: kandidatpricehistory
    skip_cleanup: true
    on:
      branch: master #vi kommer bara deploya master (inte branches)
